services:
  mariadb:
    image: mariadb
    container_name: inception-mariadb
    volumes: 
      - mariadb:/var/lib/mysql
    networks:
      - inception
    build: 
      context: services/mariadb
      dockerfile: Dockerfile
    env_file: .env
    restart: on-failure
    expose:
      - "3306"

  wordpress:
    image: wordpress
    container_name: inception-wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build: 
      context: services/wp
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - mariadb
    restart: on-failure
    expose: 
      - "9000"

  nginx:
    image: nginx
    container_name: inception-nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build: 
      context: services/nginx
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: on-failure

volumes:
  wordpress:
  mariadb:


networks:
    inception:
      driver: bridge