services:
  mariadb:
    image: mariadb
    container_name: inception-mariadb
    volumes: 
      - mariadb:/var/lib/mysql
    networks:
      - inception
    build: 
      context: services/mariadb
      dockerfile: Dockerfile
    env_file: .env
    restart: on-failure
    expose:
      - "3306"

  nginx:
    image: nginx
    container_name: inception-nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build: 
      context: services/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    image: wordpress
    container_name: inception-wordpress
    env_file: .env
    volumes:
    - wordpress:/var/www/wordpress
    networks:
      - inception
    build: 
      context: services/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    restart: on-failure
    expose: 
      - "9000"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/inception-data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/inception-data/mariadb'

networks:
    inception:
      driver: bridge