services:
  mariadb:
    image: mariadb
    container_name: inception-mariadb
    volumes: 
      - volume-db:/var/lib/mysql
    networks:
      - inception
    build: 
      context: services/mariadb
      dockerfile: Dockerfile
    env_file: .env
    restart: on-failure
    expose:
      - "3306"
    secrets:
      - db_rootpass
      - db_pass

  wordpress:
    image: wordpress
    container_name: inception-wordpress
    volumes:
      - volume-wp:/var/www/wordpress
    networks:
      - inception
    build: 
      context: services/wp
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - mariadb
    restart: on-failure
    expose: 
      - "9000"
    secrets:
      - db_pass
      - wp_adminpass
      - wp_userpass

  nginx:
    image: nginx
    container_name: inception-nginx
    volumes:
      - volume-wp:/var/www/wordpress
    networks:
      - inception
    build: 
      context: services/nginx
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: on-failure

volumes:
  volume-wp:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/volume-wp
  volume-db:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/volume-db

networks:
  inception:
    driver: bridge

secrets:
  db_rootpass:
    file: ./secrets/db_rootpass.txt
  db_pass:
    file: ./secrets/db_pass.txt
  wp_adminpass:
    file: ./secrets/wp_adminpass.txt
  wp_userpass:
    file: ./secrets/wp_userpass.txt